### ISSUE TITLE
Deprecate padding & margin token values?

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol-tokens#24]
We've discussed this briefly in code review recently, and the general consensus (at least between Craig and myself) is that the `margin` and `padding` [token values](https://github.com/mozilla/protocol-tokens/blob/master/tokens/_aliases.yml#L101-L115) are not really that useful, as they are essentially mirrors of the `spacing` tokens. Our SCSS would be easier to write and follow if we just stuck to `spacing` for padding/margin component values, and `layout` for organism-level spacing.

/cc @michaelmccombie

**Comment by craigcook** [comment]
We discussed this a bit today and the consensus was to make it so. 

I think when the separate tokens for margin and padding were first added we were still working out what the actual units would be and there was a possibility they could diverge (e.g. $padding-sm could have been 8px while $margin-sm could be 16px) but that hasn't happened and now I don't think it ever will. So let's lose the redundancy.

This will be a breaking change when it's published so we'll need to do it with care.

**Comment by alexgibson** [comment]
Sounds good - as this is a breaking change, i think we should probably do this sooner rather than later 👍

**Comment by michaelmccombie** [comment]
I'll take this on. It looks like we are going to bring in an agency to work with Protocol on a website separate to mozilla.org, so we should get all of our breaking changes in sooner rather than later.

**Comment by alexgibson** [comment]
@michaelmccombie are you still working on this? If not, I think I have capacity to take this on this week.
