### ISSUE TITLE
Icon for Get involved is not clear enough

### ISSUE THREAD

**Issue by nclm** [mozilla/protocol-tokens#29]
I noticed today the new unfolding menus in the mozilla.org navigation, and it looks and works really well. However, I can't understand what the icon for “Get involved” is meant to represent. I asked my colleague and she didn't get it either.

![screen shot 2018-12-06 at 09 35 04](https://user-images.githubusercontent.com/923008/49571684-43759980-f93a-11e8-86bd-c45cc09add63.png)

It is included in this file: [about.html](/mozilla/bedrock/blob/master/bedrock/base/templates/includes/protocol/navigation/menu/about.html)

Should it be drawn in a way that is simpler to register, or use a different metaphor?

**Comment by michaelmccombie** [comment]
I agree it's not the best icon. It's supposed to be a woman with their fist in the air. The intention was for those icons to be used as placeholders while we were working on a new illustration / icon style, so we didn't spend a lot of time on them.

We don't host icons in this repository (Icons are hosted in the assets repository https://github.com/mozilla/protocol-assets/ ) and the navigation icons will change with the rebranding (which includes a new icon system) which we are hoping to roll out soon.

**Comment by nclm** [comment]
Oh I see it now, thanks! It was a nice idea, but a bit obscure to decode :)
Thanks for the reply, looking forward to see the new illustration/icon style!
