### ISSUE TITLE
Reorder color values by color weight for Sketch consumption

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol-tokens#40]
The order that color values are exported affects the way they appear in the color fill selector for Sketch. This proposal creates a separate json file that is specifically used for Sketch consumption.

**Token Order**
```
  color-pink-80: '#7f145b'
  color-pink-90: '#50134b'

  color-red-5: '#ffdfe7'
  color-red-10: '#ffbdc5'
  color-red-20: '#ff9aa2'
```

**Sketch Order**
```
  color-violet-80: '#45278d'
  color-purple-80: '#4e1a69'

  color-pink-90: '#50134b'
  color-red-90: '#440306'
  color-orange-90: '#7c1504'
```

**Comment by reemhamz** [comment]
Closing because we no longer use Sketch as a design tool
