### ISSUE TITLE
Add "Inter" and "Metropolis" to the font-stack

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/protocol-tokens#49]
Inter is the open-source font that will be used in all of our sites, products, and marketing moving forward. This proposal replaces "Open Sans" in our font-stack with "Inter".

**Current Font Stack**
```
font-stack-sans: "'Open Sans', X-LocaleSpecific, sans-serif"
font-stack-serif: "'Zilla Slab', 'Open Sans', X-LocaleSpecific, serif"
font-stack-mono: "Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace"
```

**Proposed Font Stack**
```
font-stack-sans: "sharpsans, 'Inter', X-LocaleSpecific, sans-serif"
font-stack-serif: "'Zilla Slab', 'Inter', X-LocaleSpecific, serif"
font-stack-body: "'Inter', X-LocaleSpecific, sans-serif"
font-stack-mono: "Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace"
```

**NOTE:** The implementation of Sharp Sans is based on the Firefox Fights for You page
https://www.mozilla.org/en-US/firefox/fights-for-you/

**Comment by craigcook** [comment]
We're not using Sharp Sans on websites after all -- too many related problems and it was finally deemed untenable for online, it's strictly being used in wordmarks now. Metropolis is the open source equivalent of choice.

We also slightly revised our naming and are going with "font-base" for Inter as the general theme font and "font-mozilla" as the theme for Zilla Slab and "font-firefox" as the theme for Metropolis. This is to support different font stacks for different brands.
