### ISSUE TITLE
Are the ink colors going to be exported?

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/protocol-tokens#61]
We're being asked to use `ink-80` by @brassy- for addons.mozilla.org, but also to use colors from this new project. I can see that `color-ink-80` is defined in https://github.com/mozilla/protocol-tokens/blob/master/tokens/colors.yml, but it doesn't seem to get exported into the files in the `/dist` folder when I install the project from npm.

**Comment by alexgibson** [comment]
When building from the latest master locally, I see `$color-ink-80` exported in the `/dist` folder OK.

If you're pulling from NPM, it may just be that change hasn't been published yet. That seems to conform to what's in the [changelog](https://github.com/mozilla/protocol-tokens/blob/master/CHANGELOG.md).

Let me just check with someone else who's been working on tokens recently. We may be good to publish a new version.

**Comment by bobsilverberg** [comment]
Thanks @alexgibson. It sounds like if a new version can be published that would fix the issue.

**Comment by alexgibson** [comment]
I'll let you know as soon as it's published - likely in the next couple of hours once more folks are awake :)

**Comment by alexgibson** [comment]
Tokens 4.0.0 is now available on NPM: https://www.npmjs.com/package/@mozilla-protocol/tokens

This should fix things. If not, feel free to reopen. Thanks!
