### ISSUE TITLE
Update screen sizes and media queries

### ISSUE THREAD

**Issue by craigcook** [mozilla/protocol-tokens#71]
Our current `$screen-lg` value is `1056px` which is an unusual number and I confess I'm not sure where it came from. `1024px` is a more standard screen size, both on older desktop monitors and many current tablets. Using `1056px` as a breakpoint means we treat those screens as essentially mobile devices and deny them a desktop-friendly layout even though they have room for it. Changing to 1024 may have little impact on our layouts since the content width paired with it is only `992px` and wouldn't need to change.

There's a question of whether we need to include `screen` in our media queries. I'm not sure we do, since we're not currently distinguishing screen from any other media type, and if we did decide to separate other media (like print) those could be more explicit. So I think it may be safe to change all our media query tokens to just the min-width dimensions and omit the `screen and` part.

It was also rightly pointed out that our `$mq-short` and `$mq-tall` breakpoints are both set at `600px`, meaning if someone where to use both in a style sheet there would be a conflict where both sets of styling would apply at exactly that size. We should change <s>`$mq-tall` to `601px`</s> `$mq-short` to `599px`. (This hasn't been an issue thus far because we haven't used them much, and have never used them both at the same time, but it's a problem waiting to happen.)

- [ ] Remove `screen and` from all `$mq-*` tokens.
- [ ] Change `$screen-lg` value to `1024px`.
- [ ] Change `$mq-lg` value to `(min-width: 1024px)`
- [ ] <s>Change `$mq-tall` value to `(min-height: 601px)`</s>
- [ ] Change `$mq-short` value to `(max-height: 599px)`

**Comment by stephaniehobson** [comment]
For all our vertical break points we set the min-width to the number we're targeting. If we take the same approach with the min-height the tall mq should be 600px and short should change to 599. Does my mental model match yours here?

**Comment by craigcook** [comment]
> For all our vertical break points we set the min-width to the number we're targeting. If we take the same approach with the min-height the tall mq should be 600px and short should change to 599. Does my mental model match yours here?

You're right, that makes more sense. So a "tall window" is 600px or more, a "short window" is 599px or less.
