### ISSUE TITLE
Add a token for the zap/rainbow gradient

### ISSUE THREAD

**Issue by craigcook** [mozilla/protocol-tokens#76]
Some Firefox designs make use of a decorative rainbow gradient element called The Zap. It's usually an image but sometimes it could be a CSS background gradient. We should make a token for that gradient so we can reuse it easily and keep it consistent.

The current zap is a three-color gradient, which I would reproduce in CSS with: `background: linear-gradient(to right, #616eb3, #ec1067, #f6901e);`

However none of these colors map to current color tokens. So I think we have two options: 

1. Treat these as one-off, zap-only colors and just hardcode the hex values into the new gradient token. 
2. Revise the canonical zap gradient to use official brand token colors. It wouldn't be an exact match to the current zap, but we can get fairly close. The kind of de-saturated purplish blue (`#616eb3`) is the one that doesn't have anything close in the brand palette, so that might need to change to a more vibrant blue or violet.

**Comment by reemhamz** [comment]
I wonder if this is still relevant to work on, since we don't get many (or any) zaps in our Firefox pages to develop anymore.

**Comment by craigcook** [comment]
Might be more of a question for the branding people, but you're right that we haven't been seeing the zap as a brand element of late. If it makes a resurgence we can reopen, but for now I don't think we need a token for it.
