### ISSUE TITLE
Add tokens for vertical spacing

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/protocol-tokens#82]
From https://github.com/mozilla/protocol/issues/536 we get 

> Final spacing sizes for desktop is:
> 192px – 96px – 64px
> 
> Final spacing sizes for mobile is:
> 96px – 64px – 48px

These mostly match our existing layout tokens except for 192. We could update the value of $layout-2xl to be 192px.

Alternatively we could make specific aliases along the lines of:
```
$v-spacing-sm-on-mobile: 48px;
$v-spacing-md-on-mobile: 64px;
$v-spacing-lg-on-mobile: 96px;

$v-spacing-sm-on-desktop: 64px
$v-spacing-md-on-desktop: 96px
$v-spacing-md-on-desktop: 192px
```

**Comment by craigcook** [comment]
How about adding `$layout-3xl: 192px;` ?

**Comment by stephaniehobson** [comment]
3xl 👍

**Comment by stephaniehobson** [comment]
Changed to updating layout-2xl per https://github.com/mozilla/protocol-tokens/pull/83#issuecomment-625973432
